<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;
use App\Models\Category;

class ProductsDistributorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Asegurarse de que existan categorías
        $categoryQuesos = Category::firstOrCreate(
            ['nombre' => 'Quesos'],
            ['slug' => 'quesos', 'activo' => true, 'descripcion' => 'Variedad de quesos premium']
        );

        $categoryEmbutidos = Category::firstOrCreate(
            ['nombre' => 'Embutidos'],
            ['slug' => 'embutidos', 'activo' => true, 'descripcion' => 'Embutidos de calidad']
        );

        $categoryJamones = Category::firstOrCreate(
            ['nombre' => 'Jamones'],
            ['slug' => 'jamones', 'activo' => true, 'descripcion' => 'Jamones selectos']
        );

        // Productos de ejemplo para distribución
        $products = [
            // QUESOS
            [
                'category_id' => $categoryQuesos->id,
                'nombre' => 'Queso Manchego Curado',
                'marca' => 'La Mancha Premium',
                'descripcion' => 'Queso manchego curado de 12 meses, elaborado con leche de oveja 100% natural. Ideal para tablas de quesos y consumo directo.',
                'sku' => 'QMC-001',
                'codigo_barras' => '7501234567890',
                'precio_caja' => 1250.00,
                'precio_unidad' => 125.00,
                'precio_mayoreo' => 1150.00,
                'unidades_por_caja' => 10,
                'peso_caja' => 30.0,
                'peso_unidad' => 3.0,
                'stock' => 150,
                'cantidad_minima_pedido' => 2,
                'cantidad_mayoreo' => 10,
                'stock_alerta' => 20,
                'unidad_medida' => 'kg',
                'origen' => 'España',
                'dias_caducidad' => 90,
                'temperatura_almacenamiento' => '4-8°C',
                'destacado' => true,
                'activo' => true,
            ],
            [
                'category_id' => $categoryQuesos->id,
                'nombre' => 'Queso Oaxaca',
                'marca' => 'Lácteos del Valle',
                'descripcion' => 'Queso Oaxaca fresco, perfecto para quesadillas y platillos mexicanos. Textura suave y fácil de desmenuzar.',
                'sku' => 'QOX-002',
                'codigo_barras' => '7501234567891',
                'precio_caja' => 800.00,
                'precio_unidad' => 100.00,
                'precio_mayoreo' => 750.00,
                'unidades_por_caja' => 8,
                'peso_caja' => 24.0,
                'peso_unidad' => 3.0,
                'stock' => 200,
                'cantidad_minima_pedido' => 3,
                'cantidad_mayoreo' => 15,
                'stock_alerta' => 30,
                'unidad_medida' => 'kg',
                'origen' => 'México',
                'dias_caducidad' => 30,
                'temperatura_almacenamiento' => '2-6°C',
                'destacado' => true,
                'activo' => true,
            ],
            [
                'category_id' => $categoryQuesos->id,
                'nombre' => 'Queso Gouda Holandés',
                'marca' => 'Dutch Delights',
                'descripcion' => 'Queso Gouda auténtico holandés, cremoso y con sabor suave. Perfecto para sándwiches y aperitivos.',
                'sku' => 'QGD-003',
                'codigo_barras' => '7501234567892',
                'precio_caja' => 1400.00,
                'precio_unidad' => 140.00,
                'precio_mayoreo' => 1300.00,
                'unidades_por_caja' => 10,
                'peso_caja' => 40.0,
                'peso_unidad' => 4.0,
                'stock' => 80,
                'cantidad_minima_pedido' => 2,
                'cantidad_mayoreo' => 8,
                'stock_alerta' => 15,
                'unidad_medida' => 'kg',
                'origen' => 'Holanda',
                'dias_caducidad' => 60,
                'temperatura_almacenamiento' => '4-8°C',
                'destacado' => false,
                'activo' => true,
            ],

            // EMBUTIDOS
            [
                'category_id' => $categoryEmbutidos->id,
                'nombre' => 'Salami Milano Premium',
                'marca' => 'Italiana Delicatessen',
                'descripcion' => 'Salami Milano artesanal de cerdo seleccionado, especias naturales y curado tradicional de 60 días.',
                'sku' => 'SAL-004',
                'codigo_barras' => '7501234567893',
                'precio_caja' => 2100.00,
                'precio_unidad' => 175.00,
                'precio_mayoreo' => 1950.00,
                'unidades_por_caja' => 12,
                'peso_caja' => 18.0,
                'peso_unidad' => 1.5,
                'stock' => 120,
                'cantidad_minima_pedido' => 2,
                'cantidad_mayoreo' => 10,
                'stock_alerta' => 25,
                'unidad_medida' => 'kg',
                'origen' => 'Italia',
                'dias_caducidad' => 120,
                'temperatura_almacenamiento' => '0-4°C',
                'destacado' => true,
                'activo' => true,
            ],
            [
                'category_id' => $categoryEmbutidos->id,
                'nombre' => 'Chorizo Español Picante',
                'marca' => 'Embutidos Ibéricos',
                'descripcion' => 'Chorizo español curado con pimentón picante. Sabor intenso y auténtico, ideal para tapas y bocadillos.',
                'sku' => 'CHO-005',
                'codigo_barras' => '7501234567894',
                'precio_caja' => 1600.00,
                'precio_unidad' => 160.00,
                'precio_mayoreo' => 1480.00,
                'unidades_por_caja' => 10,
                'peso_caja' => 20.0,
                'peso_unidad' => 2.0,
                'stock' => 180,
                'cantidad_minima_pedido' => 3,
                'cantidad_mayoreo' => 12,
                'stock_alerta' => 30,
                'unidad_medida' => 'kg',
                'origen' => 'España',
                'dias_caducidad' => 90,
                'temperatura_almacenamiento' => '0-8°C',
                'destacado' => true,
                'activo' => true,
            ],
            [
                'category_id' => $categoryEmbutidos->id,
                'nombre' => 'Mortadela con Aceitunas',
                'marca' => 'Charcutería Gourmet',
                'descripcion' => 'Mortadela premium con aceitunas verdes. Textura suave y sabor delicado. Perfecta para desayunos y snacks.',
                'sku' => 'MOR-006',
                'codigo_barras' => '7501234567895',
                'precio_caja' => 950.00,
                'precio_unidad' => 95.00,
                'precio_mayoreo' => 880.00,
                'unidades_por_caja' => 10,
                'peso_caja' => 30.0,
                'peso_unidad' => 3.0,
                'stock' => 95,
                'cantidad_minima_pedido' => 2,
                'cantidad_mayoreo' => 8,
                'stock_alerta' => 20,
                'unidad_medida' => 'kg',
                'origen' => 'Italia',
                'dias_caducidad' => 45,
                'temperatura_almacenamiento' => '2-6°C',
                'destacado' => false,
                'activo' => true,
            ],

            // JAMONES
            [
                'category_id' => $categoryJamones->id,
                'nombre' => 'Jamón Serrano Reserva 18 Meses',
                'marca' => 'Jamonería Ibérica',
                'descripcion' => 'Jamón serrano de reserva con 18 meses de curación. Sabor intenso y aroma característico. Producto premium.',
                'sku' => 'JSE-007',
                'codigo_barras' => '7501234567896',
                'precio_caja' => 4500.00,
                'precio_unidad' => 450.00,
                'precio_mayoreo' => 4200.00,
                'unidades_por_caja' => 10,
                'peso_caja' => 70.0,
                'peso_unidad' => 7.0,
                'stock' => 45,
                'cantidad_minima_pedido' => 1,
                'cantidad_mayoreo' => 5,
                'stock_alerta' => 10,
                'unidad_medida' => 'kg',
                'origen' => 'España',
                'dias_caducidad' => 180,
                'temperatura_almacenamiento' => '15-20°C',
                'destacado' => true,
                'activo' => true,
            ],
            [
                'category_id' => $categoryJamones->id,
                'nombre' => 'Jamón de Pavo Ahumado',
                'marca' => 'Carnes Selectas',
                'descripcion' => 'Jamón de pavo ahumado bajo en grasa, ideal para dietas saludables. Sabor ahumado natural y textura jugosa.',
                'sku' => 'JPA-008',
                'codigo_barras' => '7501234567897',
                'precio_caja' => 1350.00,
                'precio_unidad' => 135.00,
                'precio_mayoreo' => 1250.00,
                'unidades_por_caja' => 10,
                'peso_caja' => 30.0,
                'peso_unidad' => 3.0,
                'stock' => 160,
                'cantidad_minima_pedido' => 2,
                'cantidad_mayoreo' => 10,
                'stock_alerta' => 25,
                'unidad_medida' => 'kg',
                'origen' => 'México',
                'dias_caducidad' => 60,
                'temperatura_almacenamiento' => '2-6°C',
                'destacado' => false,
                'activo' => true,
            ],
            [
                'category_id' => $categoryJamones->id,
                'nombre' => 'Jamón Ibérico de Bellota',
                'marca' => 'Dehesa Extremeña',
                'descripcion' => 'Jamón ibérico de bellota 100% puro. El producto más premium de nuestra selección. Curación de 36 meses.',
                'sku' => 'JIB-009',
                'codigo_barras' => '7501234567898',
                'precio_caja' => 12500.00,
                'precio_unidad' => 1250.00,
                'precio_mayoreo' => 11800.00,
                'unidades_por_caja' => 10,
                'peso_caja' => 80.0,
                'peso_unidad' => 8.0,
                'stock' => 25,
                'cantidad_minima_pedido' => 1,
                'cantidad_mayoreo' => 3,
                'stock_alerta' => 5,
                'unidad_medida' => 'kg',
                'origen' => 'España',
                'dias_caducidad' => 365,
                'temperatura_almacenamiento' => '15-25°C',
                'destacado' => true,
                'activo' => true,
            ],
            [
                'category_id' => $categoryJamones->id,
                'nombre' => 'Jamón York Extra',
                'marca' => 'Carnes Premium',
                'descripcion' => 'Jamón york cocido de primera calidad. Sabor suave y textura firme. Perfecto para sándwiches y bocadillos.',
                'sku' => 'JYO-010',
                'codigo_barras' => '7501234567899',
                'precio_caja' => 1100.00,
                'precio_unidad' => 110.00,
                'precio_mayoreo' => 1020.00,
                'unidades_por_caja' => 10,
                'peso_caja' => 30.0,
                'peso_unidad' => 3.0,
                'stock' => 15,
                'cantidad_minima_pedido' => 3,
                'cantidad_mayoreo' => 12,
                'stock_alerta' => 20,
                'unidad_medida' => 'kg',
                'origen' => 'México',
                'dias_caducidad' => 45,
                'temperatura_almacenamiento' => '2-6°C',
                'destacado' => false,
                'activo' => true,
            ],
        ];

        foreach ($products as $product) {
            Product::updateOrCreate(
                ['sku' => $product['sku']],
                $product
            );
        }

        $this->command->info('✅ Se han creado ' . count($products) . ' productos para distribución mayorista');
    }
}
